function [int_zz] = int_P2_Q2(Ux,Uy,Tx,aTx,Ty,aTy,g_fit)

int_zz = g_fit.p00 *Kr(Ux,Uy) + ...
    g_fit.p10 *Kr(Ux,aTy) + g_fit.p01 *Kr(aTx,Uy)+...
    g_fit.p20 *Kr(Ux,Ty*aTy) + g_fit.p11 *Kr(aTx,aTy) + g_fit.p02 *Kr(Tx*aTx,Uy)+...
    g_fit.p30 *Kr(Ux,Ty^2*Ty) + g_fit.p21 *Kr(aTx,Ty*aTy) + g_fit.p12 *Kr(Tx*aTx,aTy) +...
    g_fit.p03 *Kr(Tx^2*aTx,Uy)+...
    g_fit.p40 *Kr(Ux,Ty^3*aTy) + g_fit.p31 *Kr(aTx,Ty^2*aTy) + g_fit.p22 *Kr(Tx*aTx,Ty*aTy) +...
        g_fit.p13 *Kr(Tx^2*aTx,aTy) + g_fit.p04 *Kr(Tx^3*aTx,Uy)+...
    g_fit.p50 *Kr(Ux,Ty^4*aTy) + g_fit.p41 *Kr(aTx,Ty^3*aTy) + g_fit.p32 *Kr(Tx*aTx,Ty^2*aTy) +...
        g_fit.p23 *Kr(Tx^2*aTx,Ty*aTy) + g_fit.p14 *Kr(Tx^3*aTx,aTy) + g_fit.p05 *Kr(Tx^4*aTx,Uy);
    